[package]
name = "yew-app"
version = "0.1.0"
authors = ["Kazuki Tsutsumi <rixi223.kazuki@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.16"
wasm-bindgen = "0.2"